yml terminado

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -260,14 +260,14 @@ stages:
               PathtoPublish: '$(Build.ArtifactStagingDirectory)'
             displayName: 'Publicar artefactos'
 
-  # =========================
+    # =========================
   # 3) QA
   # =========================
   - stage: Deploy_QA
     displayName: "Deploy QA"
     dependsOn: Build
     variables:
-      - group: VG_QA
+      - group: VG_QA     # <- Variable Group QA
     jobs:
       - deployment: QADeploy
         displayName: 'Deploy a QA'
@@ -288,47 +288,63 @@ stages:
                   displayName: 'Deploy Backend QA'
                   inputs:
                     azureSubscription: 'sc-azure-appweb'
+
                     appName: '$(webAppNameBack)'
                     package: '$(Pipeline.Workspace)/drop/backend.zip'
 
+
+                # Setear App Settings (DB, etc.) por si cambian
                 - task: AzureAppServiceSettings@1
                   displayName: 'App Settings Backend QA'
                   inputs:
                     azureSubscription: 'sc-azure-appweb'
+
                     appName: '$(webAppNameBack)'
                     appSettings: |
                       [
-                        {"name":"DB_HOST","value":"$(DB_HOST)"},
-                        {"name":"DB_PORT","value":"$(DB_PORT)"},
-                        {"name":"DB_NAME","value":"$(DB_NAME)"},
-                        {"name":"DB_USER","value":"$(DB_USER)"},
-                        {"name":"DB_PASSWORD","value":"$(DB_PASSWORD)"},
-                        {"name":"DB_SSLMODE","value":"$(DB_SSLMODE)"},
-                        {"name":"PORT","value":"8080"}
+                        {"name":"DB_HOST","value":"$(DB_HOST)","slotSetting":false},
+                        {"name":"DB_PORT","value":"$(DB_PORT)","slotSetting":false},
+                        {"name":"DB_NAME","value":"$(DB_NAME)","slotSetting":false},
+                        {"name":"DB_USER","value":"$(DB_USER)","slotSetting":false},
+                        {"name":"DB_PASSWORD","value":"$(DB_PASSWORD)","slotSetting":false},
+                        {"name":"DB_SSLMODE","value":"$(DB_SSLMODE)","slotSetting":false},
+                        {"name":"PORT","value":"8080","slotSetting":false}
                       ]
 
+                # Health check backend
                 - script: |
                     BACK_URL="https://appweb-api-qa-cjc6b0hpbkbxgvf6.northcentralus-01.azurewebsites.net/api/healthz"
                     echo "Checking $BACK_URL"
                     for i in {1..10}; do
                       code=$(curl -s -o /dev/null -w "%{http_code}" "$BACK_URL")
                       echo "Intento $i => $code"
-                      if [ "$code" = "200" ]; then exit 0; fi
+                      if [ "$code" = "200" ]; then
+                        exit 0
+                      fi
                       sleep 5
                     done
-                    echo "Health check backend FAILED"; exit 1
+                    echo "Health check backend FAILED"
+                    exit 1
                   displayName: 'Health check Backend QA'
 
                 # --- FRONTEND QA ---
+                # Volvemos a construir el front con la variable VITE_API_URL de QA
                 - task: NodeTool@0
                   inputs:
                     versionSpec: '20.x'
                 - script: |
+                    echo "📂 Carpeta actual:"
+                    pwd
+                    echo "📄 Contenido:"
+                    ls -la
                     echo "Usando VITE_API_URL=$(VITE_API_URL)"
+
                     cd frontend
                     npm ci
                     VITE_API_URL=$(VITE_API_URL) npm run build
                   displayName: 'Build Vite con vars QA'
+
+
 
                 - task: ArchiveFiles@2
                   inputs:
@@ -338,21 +354,137 @@ stages:
                     archiveFile: '$(Pipeline.Workspace)/drop/frontend-qa.zip'
                   displayName: 'Empaquetar frontend QA'
 
+
                 - task: AzureWebApp@1
                   displayName: 'Deploy Frontend QA'
                   inputs:
                     azureSubscription: 'sc-azure-appweb'
+
                     appName: '$(webAppNameFront)'
                     package: '$(Pipeline.Workspace)/drop/frontend-qa.zip'
 
+
+
+                # Health check frontend
                 - script: |
                     FRONT_URL="https://appweb-front-qa-ctg3cwawggeag6g4.northcentralus-01.azurewebsites.net/"
                     echo "Checking $FRONT_URL"
                     for i in {1..10}; do
                       code=$(curl -s -o /dev/null -w "%{http_code}" "$FRONT_URL")
                       echo "Intento $i => $code"
-                      if [ "$code" = "200" ]; then exit 0; fi
+                      if [ "$code" = "200" ]; then
+                        exit 0
+                      fi
                       sleep 5
                     done
-                    echo "Health check frontend FAILED"; exit 1
+                    echo "Health check frontend FAILED"
+                    exit 1
                   displayName: 'Health check Frontend QA'
+
+  # =========================
+  # 4) PRODUCCIÓN (con aprobación)
+  # =========================
+  - stage: Deploy_Prod
+    displayName: "Deploy Producción"
+    dependsOn: Deploy_QA
+    variables:
+      - group: VG_PROD   # <- Variable Group PROD
+    jobs:
+      - deployment: ProdDeploy
+        displayName: 'Deploy a Producción'
+        environment: 'Production'   # <- este env tiene aprobación manual
+        strategy:
+          runOnce:
+            deploy:
+              steps:
+                - checkout: self
+                  clean: true
+                  persistCredentials: true
+
+                - download: current
+                  artifact: drop
+
+                # BACKEND PROD
+                - task: AzureWebApp@1
+                  displayName: 'Deploy Backend PROD'
+                  inputs:
+                    azureSubscription: 'sc-azure-appweb'
+
+                    appName: '$(webAppNameBack)'
+                    package: '$(Pipeline.Workspace)/drop/backend.zip'
+
+                - task: AzureAppServiceSettings@1
+                  displayName: 'App Settings Backend PROD'
+                  inputs:
+                    azureSubscription: 'sc-azure-appweb'
+
+                    appName: '$(webAppNameBack)'
+                    appSettings: |
+                      [
+                        {"name":"DB_HOST","value":"$(DB_HOST)","slotSetting":false},
+                        {"name":"DB_PORT","value":"$(DB_PORT)","slotSetting":false},
+                        {"name":"DB_NAME","value":"$(DB_NAME)","slotSetting":false},
+                        {"name":"DB_USER","value":"$(DB_USER)","slotSetting":false},
+                        {"name":"DB_PASSWORD","value":"$(DB_PASSWORD)","slotSetting":false},
+                        {"name":"DB_SSLMODE","value":"$(DB_SSLMODE)","slotSetting":false},
+                        {"name":"PORT","value":"8080","slotSetting":false}
+                      ]
+
+                - script: |
+                    BACK_URL="https://appweb-api-prod-hdhgb2bmb6eyaubv.chilecentral-01.azurewebsites.net/api/healthz"
+                    echo "Checking $BACK_URL"
+                    for i in {1..10}; do
+                      code=$(curl -s -o /dev/null -w "%{http_code}" "$BACK_URL")
+                      echo "Intento $i => $code"
+                      if [ "$code" = "200" ]; then
+                        exit 0
+                      fi
+                      sleep 5
+                    done
+                    echo "Health check backend PROD FAILED"
+                    exit 1
+                  displayName: 'Health check Backend PROD'
+
+
+                # FRONTEND PROD (rebuild con URL de PROD)
+                - task: NodeTool@0
+                  inputs:
+                    versionSpec: '20.x'
+                - script: |
+                    cd frontend
+                    echo "Usando VITE_API_URL=$(VITE_API_URL)"
+                    npm ci
+                    VITE_API_URL=$(VITE_API_URL) npm run build
+                  displayName: 'Build Vite con vars PROD'
+
+
+                - task: ArchiveFiles@2
+                  inputs:
+                    rootFolderOrFile: 'frontend/dist'
+                    includeRootFolder: false
+                    archiveType: 'zip'
+                    archiveFile: '$(Pipeline.Workspace)/drop/frontend-prod.zip'
+                  displayName: 'Empaquetar frontend PROD'
+
+                - task: AzureWebApp@1
+                  displayName: 'Deploy Frontend PROD'
+                  inputs:
+                    azureSubscription: 'sc-azure-appweb'
+
+                    appName: '$(webAppNameFront)'
+                    package: '$(Pipeline.Workspace)/drop/frontend-prod.zip'
+
+                - script: |
+                    FRONT_URL="https://appweb-front-prod-h7htdzbchbhsf6g2.northcentralus-01.azurewebsites.net/"
+                    echo "Checking $FRONT_URL"
+                    for i in {1..10}; do
+                      code=$(curl -s -o /dev/null -w "%{http_code}" "$FRONT_URL")
+                      echo "Intento $i => $code"
+                      if [ "$code" = "200" ]; then
+                        exit 0
+                      fi
+                      sleep 5
+                    done
+                    echo "Health check frontend PROD FAILED"
+                    exit 1
+                  displayName: 'Health check Frontend PROD'
